name: 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  terraform:
    name: Ensure environment is up-to-date
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v1
      with:
        do_token: ${{ secrets.DO_TOKEN }}

    - name: Format TF
      run: terraform fmt terraform/

    - name: Plan TF
      run: terraform -chdir=terraform plan
