name: 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  terraform:
    name: Ensure environment is up-to-date
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v1

    - name: Initialize Terraform
      run: terraform -chdir=terraform init

    - name: Format Terraform
      run: terraform fmt terraform/

    - name: Plan Terraform
      run: terraform -chdir=terraform plan -out=planfile
      env:
        TF_VAR_do_token: ${{ secrets.DO_TOKEN }}
    
    - name: Plan Terraform
      run: terraform -chdir=terraform apply --auto-approve planfile
      env:
        TF_VAR_do_token: ${{ secrets.DO_TOKEN }}
