name: TEST Deployment
on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]
  workflow_dispatch:
jobs:
  init:
    name: Deploy TEST infrastructure
    runs-on: ubuntu-latest
    env:
      TF_VAR_do_token: ${{ secrets.DO_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.DO_SPACES_TOKEN }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DO_SPACES_SECRET }}

    steps:
    - uses: actions/checkout@v2
    - uses: hashicorp/setup-terraform@v1

    - name: Initialize Terraform
      run: terraform -chdir=terraform/test init

    - name: Format Terraform
      run: terraform fmt terraform/test/

    - name: Plan Terraform
      run: terraform -chdir=terraform/test plan -out=planfile
   
    - name: Apply Terraform
      run: terraform -chdir=terraform/test apply --auto-approve planfile

  deploy:
    name: Deploy Website to TEST
    runs-on: ubuntu-latest
    env:
      PRIVATE_KEY: ${{ secrets.TEST_SSH_KEY }}

    steps:
    - name: ls -a via ssh
      uses: fifsky/ssh-action@master
      with:
        command: |
          cd /tmp
          ls -a
        host: test.schild.tech
        user: root
        key: ${{ secrets.TEST_SSH_KEY}}